Check main.yml LilyPond SHA

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,18 +34,24 @@ jobs:
     - name: Install LilyPond
       run: |
         lilypond_version=2.25.22
-        lilypond_archive=lilypond-${lilypond_version}-linux-x86_64.tar.gz
-        lilypond_url=https://gitlab.com/lilypond/lilypond/-/releases/
-        lilypond_url=${lilypond_url}/v${lilypond_version}/downloads/${lilypond_archive}
-        echo ${lilypond_url}
-        cd /tmp
+        lilypond_archive="lilypond-${lilypond_version}-linux-x86_64.tar.gz"
+        lilypond_url="https://gitlab.com/lilypond/lilypond/-/releases/v${lilypond_version}/downloads/${lilypond_archive}"
+        echo "Downloading LilyPond from: ${lilypond_url}"
+        cd /tmp || { echo "Failed to change directory to /tmp"; exit 1; }
         wget -q ${lilypond_url}
-        checksum="f0e6e441bd336b8f37d1021ad1365b3fd188e310820d"
-        if ! echo "${checksum}  ${lilypond_archive}" | sha256sum -c --status; then
-          echo "Checksum verification failed!" >&2
-          exit 1
+        if [ ! -f "${lilypond_archive}" ]; then
+            echo "File download failed!" >&2
+            exit 1
         fi
-        tar -xf ${lilypond_archive}
+        checksum="f0e6e441bd336b8f37d1021ad1365b3fd188e310820d"
+        echo "${checksum}  ${lilypond_archive}" > checksum.txt
+        if ! sha256sum -c checksum.txt --status; then
+            echo "Checksum verification failed!" >&2
+            exit 1
+        fi
+        rm checksum.txt
+        echo "Checksum verified successfully."
+        tar -xf "${lilypond_archive}"
     - name: Install Abjad
       run: |
         export PATH=/tmp/lilypond-2.25.22/bin:/home/runner/bin:$PATH
