Check main.yml LilyPond SHA (#1618)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,7 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ["3.12", "3.13", "3.14-dev"]
+        python-version: ["3.12", "3.13"]
 
     steps:
     - uses: actions/checkout@v2
@@ -34,13 +34,24 @@ jobs:
     - name: Install LilyPond
       run: |
         lilypond_version=2.25.22
-        lilypond_archive=lilypond-${lilypond_version}-linux-x86_64.tar.gz
-        lilypond_url=https://gitlab.com/lilypond/lilypond/-/releases/
-        lilypond_url=${lilypond_url}/v${lilypond_version}/downloads/${lilypond_archive}
-        echo ${lilypond_url}
-        cd /tmp
+        lilypond_archive="lilypond-${lilypond_version}-linux-x86_64.tar.gz"
+        lilypond_url="https://gitlab.com/lilypond/lilypond/-/releases/v${lilypond_version}/downloads/${lilypond_archive}"
+        echo "Downloading LilyPond from: ${lilypond_url}"
+        cd /tmp || { echo "Failed to change directory to /tmp"; exit 1; }
         wget -q ${lilypond_url}
-        tar -xf ${lilypond_archive}
+        if [ ! -f "${lilypond_archive}" ]; then
+            echo "File download failed!" >&2
+            exit 1
+        fi
+        checksum="3e837e811aaa72323863925f0a4b5bd1aff1ed9b997e6c70dbe5c008e47872e7"
+        echo "${checksum}  ${lilypond_archive}" > checksum.txt
+        if ! sha256sum -c checksum.txt --status; then
+            echo "Checksum verification failed!" >&2
+            exit 1
+        fi
+        rm checksum.txt
+        echo "Checksum verified successfully."
+        tar -xf "${lilypond_archive}"
     - name: Install Abjad
       run: |
         export PATH=/tmp/lilypond-2.25.22/bin:/home/runner/bin:$PATH
